version: "3"

services:
  postgres:
    container_name: postgr
    image: postgres:13
    command: postgres
    environment:
      POSTGRES_USER: "gym_user"
      POSTGRES_PASSWORD: "gym_password"
      POSTGRES_DB: "gymdb"
    ports:
      - "5433:5432"

  apps:
    container_name: gymapp
    build: .
    ports:
      - "8080:8080"
    network_mode: host
    depends_on:
      - postgres

